// Generated by tools/art/blink/eyes.py: each figure's eye band [x0, y0, x1, y1] in its head sheet's front view
// (pixels of that view, cut as tools/art/blink/<who>_open.png); assets/blink/<who>.webp is the same band with the eyes closed.
export const BLINK = {
  celeste: [234, 202, 516, 284, 22, 1086],
  cherry: [186, 343, 438, 455, 0, 1086],
  dex: [185, 233, 502, 348, 21, 1086],
  gus: [171, 189, 534, 305, 25, 1086],
  harper: [122, 328, 465, 448, 0, 941],
  jojo: [183, 239, 480, 325, 39, 1086],
  juniper: [213, 188, 541, 347, 13, 1086],
  kenji: [79, 383, 416, 494, 18, 1086],
  nate: [207, 201, 509, 282, 13, 1086],
  opal: [188, 211, 509, 324, 24, 1086],
  priya: [72, 264, 398, 377, 214, 1086],
  rashad: [167, 239, 485, 348, 47, 1086],
  regent: [75, 258, 381, 375, 202, 1086],
  silas: [87, 269, 436, 382, 115, 1086],
};
