# Eye bands for blinking: python tools/art/blink/eyes.py <who> ...
# Needs <who>_open.png (the head sheet's front view, cut by this folder's crop step) and <who>_closed.png (the same,
# eyes closed, from ChatGPT). Aligns the closed version to the open one (scale + shift, matched on the nose and mouth),
# finds the eyes by face landmarks, and writes assets/blink/<who>.webp (the eye band, eyes closed) plus the band's
# place in the head sheet's front cell to js/figblink.js.
import os, sys, json, re, numpy as np, cv2
import mediapipe as mp
from mediapipe.tasks import python as mpp
from mediapipe.tasks.python import vision
D = os.path.dirname(os.path.abspath(__file__)); R = os.path.join(D, '..', '..', '..')
fl = vision.FaceLandmarker.create_from_options(vision.FaceLandmarkerOptions(base_options=mpp.BaseOptions(model_asset_path=os.path.join(R, 'tools', 'figures', 'mp', 'face_landmarker.task')),
    num_faces=1, min_face_detection_confidence=0.2, min_face_presence_confidence=0.2))
def lm(bgr):
    r = fl.detect(mp.Image(image_format=mp.ImageFormat.SRGB, data=np.ascontiguousarray(cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB))))
    return np.array([[q.x * bgr.shape[1], q.y * bgr.shape[0]] for q in r.face_landmarks[0]]) if r.face_landmarks else None
out = {}
jp = os.path.join(R, 'js', 'figblink.js')
if os.path.exists(jp):
    import re
    for m in re.finditer(r"  (\w+): \[([^\]]*)\]", open(jp).read()): out[m.group(1)] = [float(x) for x in m.group(2).split(',')]
for who in sys.argv[1:]:
    op = cv2.imread(os.path.join(D, who + '_open.png')); cl = cv2.imread(os.path.join(D, who + '_closed.png'))
    H, W = op.shape[:2]; cl = cv2.resize(cl, (W, H), interpolation=cv2.INTER_AREA)
    L0, L1 = lm(op), lm(cl)
    assert L0 is not None, who + ': no face in the open image'
    # align by the landmarks that don't move with the eyes (nose, mouth, jaw); fall back to the whole picture
    keep = list(range(0, 18)) + [1, 2, 4, 5, 6, 19, 94, 164, 197, 195, 61, 291, 13, 14, 17, 152, 234, 454, 93, 323]
    if L1 is not None:
        a, b = L1[keep], L0[keep]; ac, bc = a - a.mean(0), b - b.mean(0)
        s = (ac * bc).sum() / (ac * ac).sum(); t = b.mean(0) - s * a.mean(0)
    else: s, t = 1.0, np.zeros(2)
    M = np.array([[s, 0, t[0]], [0, s, t[1]]], np.float32); clA = cv2.warpAffine(cl, M, (W, H), flags=cv2.INTER_LINEAR, borderMode=cv2.BORDER_REPLICATE)
    # the eye band: from above the brows to below the eyes, across both eyes, with a margin
    eyes = L0[[33, 133, 160, 144, 362, 263, 385, 380, 70, 105, 107, 336, 334, 300, 46, 276]]
    x0, x1 = eyes[:, 0].min(), eyes[:, 0].max(); y0, y1 = eyes[:, 1].min(), eyes[:, 1].max()
    mx, my = (x1 - x0) * 0.18, (y1 - y0) * 0.35
    x0, x1, y0, y1 = [int(round(v)) for v in (max(0, x0 - mx), min(W, x1 + mx), max(0, y0 - my), min(H, y1 + my))]
    band = clA[y0:y1, x0:x1].copy()
    # feather the band's edges into the open painting, so the swap never shows a rectangle
    ob = op[y0:y1, x0:x1].astype(np.float32); bb = band.astype(np.float32)
    h, w = bb.shape[:2]; yy, xx = np.mgrid[0:h, 0:w]
    fe = np.minimum(np.minimum(xx, w - 1 - xx) / (w * 0.12), np.minimum(yy, h - 1 - yy) / (h * 0.22)).clip(0, 1)[..., None]
    band = (ob + (bb - ob) * fe).astype(np.uint8)
    diff = float(np.abs(bb - ob).mean())
    os.makedirs(os.path.join(R, 'assets', 'blink'), exist_ok=True)
    cv2.imwrite(os.path.join(R, 'assets', 'blink', who + '.webp'), band, [cv2.IMWRITE_WEBP_QUALITY, 88])
    cv2.imwrite(os.path.join(D, who + '_check.jpg'), np.concatenate([op[y0 - 40:y1 + 40, x0 - 40:x1 + 40], np.pad(clA, 0)[y0 - 40:y1 + 40, x0 - 40:x1 + 40]], 1))
    # where this view sits in the atlas: its first opaque column in the head sheet, and the body sheet's height above it
    hs = cv2.imread(os.path.join(R, 'tools', 'figures', 'refs', who + '_head.png'), cv2.IMREAD_UNCHANGED)
    occ = (hs[..., 3] > 128).sum(0) > 2; runs = []; c0 = None
    for c in range(hs.shape[1] + 1):
        o = c < hs.shape[1] and occ[c]
        if o and c0 is None: c0 = c
        if not o and c0 is not None: runs.append((c0, c)); c0 = None
    runs = [r for r in runs if r[1] - r[0] > hs.shape[1] * 0.08]; cellX = runs[0][0] if len(runs) == 3 else 0
    A = json.loads(re.search(who + r": \{ A: (\[[^\]]*\])", open(os.path.join(R, 'js', 'figheads.js')).read()).group(1))
    out[who] = [x0, y0, x1, y1, cellX, A[1] - hs.shape[0]]
    print(who, 'band', (x0, y0, x1, y1), 'scale', round(float(s), 3), 'shift', t.round(1).tolist(), 'change in band', round(diff, 1), 'landmarks on closed' if L1 is not None else 'NO landmarks on closed (unaligned)')
open(jp, 'w', newline='\n').write("// Generated by tools/art/blink/eyes.py: each figure's eye band [x0, y0, x1, y1] in its head sheet's front view\n// (pixels of that view, cut as tools/art/blink/<who>_open.png); assets/blink/<who>.webp is the same band with the eyes closed.\nexport const BLINK = {\n" + ''.join(f"  {k}: [{', '.join(str(int(v)) for v in out[k])}],\n" for k in sorted(out)) + "};\n")
