# Collect every <name>_head.json (written by turn_build.py when a head sheet is used) into js/figheads.js,
# which the game's figure shader reads to look heads up in the sharper head sheet.
import os, json, glob
D = os.path.dirname(os.path.abspath(__file__))
out = {}
for f in sorted(glob.glob(os.path.join(D, '*_head.json'))):
    out[os.path.basename(f)[:-10]] = json.load(open(f))
r = lambda v: [round(x, 4) for x in v]
body = ',\n'.join(f"  {k}: {{ A: {json.dumps(v['A'])}, f: {json.dumps(r(v.get('f', [0, 0, 1, 1])))}, s: {json.dumps([round(x, 5) for x in v.get('s', [0, 0])])}, z: {round(v.get('z', 0), 4)}, v: [{', '.join(json.dumps(r(x)) for x in v['v'])}] }}" for k, v in out.items())
open(os.path.join(D, '..', '..', 'js', 'figheads.js'), 'w', newline='\n').write(
    "// Generated by tools/figures/heads_js.py: where each figure's head sits in its texture's head-sheet part.\n"
    "// A: atlas size (px); f: the face oval in the front view [cx, cy, rx, ry]; s: texture u per metre of depth in the two side paintings; z: the head's middle depth (m); v: per body view [x0, x1, chin row, neck row, sx, sy, ox, oy]: a body-sheet pixel (x, y) above\n"
    "// the neck maps to (sx * x + ox, sy * y + oy) in the atlas, fading in from the neck to the chin.\n"
    "export const HEADMAP = {\n" + body + "\n};\n")
print('heads:', ', '.join(out))
